name: test
on: [pull_request]
jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 
        
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        
    - name: Check env  
      run:  |
        go env
        gcc -v
        g++ -v
      
    - name: Test  
      run:  go test -p 1 ./... --coverprofile="coverage.out"  

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
