name: test
on: [pull_request]
jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.6'

    - name: Test
      env:
          CGO_ENABLED: 1  
      run:  go test ./... --coverprofile="coverage.out"  

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
