name: test and scan
on: [pull_request]
jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Install dcmtk
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: dcmtk
        
    - name: Start dcmqrscp 
      run: |
        storescp +xa -aet SCP 1105 &
        dcmqrscp -c samples/dcmqrscp.cfg +xs &

    - name: Test
      env:
        CGO_ENABLED: 1   
      run:  go test -p 1 -tags jpeg2000 ./... --coverprofile="coverage.out"  

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
